### ISSUE TITLE
KM2 Error in Logfile

### ISSUE THREAD

**Issue by Dickschieder** [Grizzelbee/ioBroker.resol#108]
Hello,
i installed the ioBroker Adapter and it's working fine. I'm using the KM2, but I always get the error in logfile with this information:

`Error: Unable to complete value {"key":0,"value":{"valueId":"Handbetrieb"}}`
![image](https://user-images.githubusercontent.com/49694768/169880083-4ea28295-8da2-4807-a5ca-8704f2f0529b.png)

How can I solve this?

best regards
Sebastian

**Comment by Grizzelbee** [comment]
I assume that it's caused by the congtroller - not the KM2. The KM2 does only the data transfer.
Please write a debug log from the start of the adapter up to the error and post it here. 
With that I can take a look what's causing the issue.

**Comment by Dickschieder** [comment]
hello @Grizzelbee thanks
here is the logfile after restarting the resol adapter.

[iobroker.2022-05-24.log.pdf](https://github.com/Grizzelbee/ioBroker.resol/files/8759916/iobroker.2022-05-24.log.pdf)

**Comment by Dickschieder** [comment]
@Grizzelbee 
Hi, did you find anything? In version 1.2.0 it's still the same in log

**Comment by kriegeru** [comment]
Hello, I get the same error in the log. My device is DeltaSol SLT.
When I make changes in the file "lib\resol-setup\deltasol-slt.js" the errormessage changes too. But i don't find the right statement.

![image](https://user-images.githubusercontent.com/43703286/198886708-de5d72a2-769e-4012-bc8c-7701b0182a5d.png)

**Comment by Grizzelbee** [comment]
Your Issue with the resol adapter should be fixed in v1.3.0

**Comment by kriegeru** [comment]
Hello, I have updated the Adapter to Version 1.3.0, but the error is still present. Here is a clipping of the actual log.
![image](https://user-images.githubusercontent.com/43703286/200175096-88abbf6f-ada6-43a3-9b4d-373a463847cb.png)

Many greats and thanks for help

**Comment by Dickschieder** [comment]
I've still the same issue with KM2. The only difference is, before there was "valueID":"Handbetrieb" and now it's "valueID":"Handbetrieb1"

**Comment by deepdreams71** [comment]
Hi , I have the same issue with KM2 / Deltasol SLT

Error: Unable to complete value {"key":0,"value":{"valueId":"Handbetrieb"}}

is there any fix planned? 

As Resol I have a DeltaSol SLT Firmeware 2.0.5

**Comment by backlink-market** [comment]
I have the same issue. Is there something available to fix it?

**Comment by Dickschieder** [comment]
Hello @backlink-market 
no, there is still the same issue. With the last version it changes only from "Handbetrieb" to "Handbetrieb1", but the values are still correct.
![image](https://github.com/Grizzelbee/ioBroker.resol/assets/49694768/1de6538c-79cf-4bc6-8254-7b9284a39cfe)

**Comment by Dickschieder** [comment]
I'm sorry,

I mean the data point values are ok. Maybe I found a temporary solution. I guess, the adapter will add a function which not exist. So I changed the file
nano /opt/iobroker/node_modules/iobroker.resol/lib/resol-setup/deltasol-bx-plus.js

and removed the function "Pumpe1"
After that, I restarted the adapter. I got an error, that the function is not found, but it was only one time. After that the logfile was clean of RESOL

regards Sebastian

**Comment by backlink-market** [comment]
Hi,

I removed the whole content of this file because I got repeating errors when I just delete the fct from the Json. 
So, now the file contains just: { }
Then I just receive this errors on start but not repeating:

resol.0 | 2023-06-12 15:21:43.836 | error | [generateDP] Error: TypeError: Cannot read properties of undefined (reading 'setup')
resol.0 | 2023-06-12 15:21:43.834 | warn | [getJSONByResolId] Controller type not found in setup file.

Think thats fine. The values are pulled correctly

**Comment by backlink-market** [comment]
hum, it getting even worse now:
![Screenshot_10](https://github.com/Grizzelbee/ioBroker.resol/assets/72196501/b9a2591b-e2a0-47b1-bff8-2339e92efa74)


TypeError: Cannot read properties of undefined (reading 'forEach')

What about your solution? @Dickschieder Can you post your file content?

**Comment by backlink-market** [comment]
My file (deltasol-bx-plus.js) looks like this now: 

```
{"dp": [{"dpName":"Pumpe1", "name":"Manual control for this relay.", "type":"number","min":0, "max":2, "states":{"0":"Off", "1":"Auto", "2":"On"}}
],
	"fct": []
}

```
And this one gives just a error on start but no more. I am ok. with that. Nevertheless, @Grizzelbee should have a look at it to fix it permantently.

**Comment by Dickschieder** [comment]
> hum, it getting even worse now: !
> 
> TypeError: Cannot read properties of undefined (reading 'forEach')
> 
> What about your solution? @Dickschieder Can you post your file content?
> 
> @Grizzelbee Can you please have a look at it? Thank you

hi @backlink-market 

I have also only the start errors. My file ist like this:

> //{"dp": [{"dpName":"Pumpe1", "name":"Manual control for this relay.", "type":"number","min":0, "max":2, "states":{"0":"Off", "1":"Auto", "2":"On"}}
//],
//      "fct": [{"name":"Pumpe1","cmd":"Handbetrieb1","val":"val"}
//]}

**Comment by backlink-market** [comment]
Getting more Errors now: TypeError: Cannot read properties of undefined (reading 'cmd')
![Screenshot_1](https://github.com/Grizzelbee/ioBroker.resol/assets/72196501/d142dc3f-0cb2-4788-a581-505184ad65a5)

How to solve that?

**Comment by Dickschieder** [comment]
@backlink-market I'm sorry - I'm not a developer. In my Log it's different
![image](https://github.com/Grizzelbee/ioBroker.resol/assets/49694768/d9dd32cb-9f36-4c0f-b18d-ac38f01c0d18)
But I'm running a newer node.js version and have a Linux Debian. But I think it doesn't matter.

Maybe you can switch the adapter to debug and see a little bit more whats happen.
![image](https://github.com/Grizzelbee/ioBroker.resol/assets/49694768/4e4d742f-75ff-4ada-9413-92e7f40a595c)

**Comment by backlink-market** [comment]
I let it run in the debug, the error doesn't come up.
Now I've put it back to normal and so far the error hasn't come back. But last time it also took a bit until the error came.
 I'll keep an eye on it and update you.

**Comment by backlink-market** [comment]
unfortunately, the errors are back and spamming my logs every 30s 
![Screenshot_2](https://github.com/Grizzelbee/ioBroker.resol/assets/72196501/4a50908e-761b-4c25-9aa8-54dfaf126c91)

**Comment by Dickschieder** [comment]
hello @backlink-market 
you have two instances of resol adapter. Is this right? You have two KM2 adapter?
here is a screenshot of my settings - maybe there is something different.
![image](https://github.com/Grizzelbee/ioBroker.resol/assets/49694768/083c3135-d5af-4eea-b58e-df37c40f3ed7)
What about the debug? Are there any new information?

**Comment by backlink-market** [comment]
yes, that correct. In fact I got 2 DeltaSol BX Plus and one DL3.
Since DL3 seems to allow only one channel per instance I have to set up 2 instances one with Channel 1 and another one with channel 2
