### ISSUE TITLE
Warning and error message when instance is started

### ISSUE THREAD

**Issue by UweSauter** [Grizzelbee/ioBroker.resol#96]
Hi again.

When starting an instance of ioBroker.resol (v1.0.0) with a VBus/Lan configuration and an attached (Cosmo Multi2)[https://www.cosmo-info.de/produkte/heizungstechnik/solartechnik/regelungen/regelung-multi-2] I get one warning and one error during startup:

- info | starting.  Version 1.0.0 (non-npm: grizzelbee/ioBroker.resol) in  /opt/iobroker/node_modules/iobroker.resol, node: v16.13.1,  js-controller: 4.0.23
- info | Config seems to be valid for LAN or LAN-Gateway.
- info | TCP Connection via LAN to [192.168.55.224:7053] selected
- info | Waiting for Connection...
- info | Connection state changed to CONNECTING
- info | Connection established
- warn | [getJSONByResolId] Controller type not found in setup file.
- error | [generateDP] Error: TypeError: Cannot read properties of undefined (reading 'setup')

Once started the instance can read sensors as expected.
Is this normal?

ioBroker is at v4.0.23

**Comment by Grizzelbee** [comment]
>    warn | [getJSONByResolId] Controller type not found in setup file.
>    error | [generateDP] Error: TypeError: Cannot read properties of undefined (reading 'setup')

> Is this normal?

Basically: Yes. This adapter is designed to support Resol-Controllers.
And to identify the actual controller a controller-ID is used. It makes sense, that Cosmo uses different IDs than Resol. But the Cosmo IDs are currently unknown to the adapter. Thats why this error occurs.
This ID is not really important for reading the values (thats why this part works) but if you like to control pumps or things like that, it's important. The various controllers support very different features.

To get that fixed please switch the adapter to debug loglevel, start it and post the log here. Your actual ID should be mentioned there and I can implement this feature than.

**Comment by UweSauter** [comment]
[debug.resol.0.zip](https://github.com/Grizzelbee/ioBroker.resol/files/8580437/debug.resol.0.zip)

This is the zipped HTML output.

**Comment by Grizzelbee** [comment]
V1.1.0 should fix your issue and add basic support for your controller.
But it's only basic support. Unfortunately I can't support all various controllers the same way. If you need more control of your controller you may need to do some investigation and configuration on your own. I'll only may be able to give you some hints.

**Comment by UweSauter** [comment]
With v1.1.0 new errors happen:

[debug.resol.0.zip](https://github.com/Grizzelbee/ioBroker.resol/files/8581249/debug.resol.0.zip)

**Comment by Grizzelbee** [comment]
Was a wrong file name. V1.1.1 should fix it.

**Comment by UweSauter** [comment]
Those two warnings still exist in 1.1.1:

`[getJSONByResolId] Error: SyntaxError: Unexpected token / in JSON at position 832`

`[generateDP] Error: TypeError: Cannot read properties of undefined (reading 'setup')`

**Comment by Grizzelbee** [comment]
Okay. Next try. V1.1.2 - That happens when you can't test things yourself. ;o)

**Comment by UweSauter** [comment]
No problem. I was more concerned that I keep you from something else :grin: 

Will test and report back in a few.

**Comment by UweSauter** [comment]
Next iteration, new error: `Unable to create optimizer for master with address 0x7821`

[debug.resol.0.zip](https://github.com/Grizzelbee/ioBroker.resol/files/8581551/debug.resol.0.zip)

**Comment by Grizzelbee** [comment]
Okay - one step deeper. This error requires a deeper dive and maybe a mapping for Cosmo controllers to Resol since this crash happens inside the resol-library.
Will take a bit longer ...

**Comment by UweSauter** [comment]
If I can provide any assistance, please feel free to get back to me.

**Comment by Grizzelbee** [comment]
Another try ... I'm trying to fake a DeltaSol-E to the library for writing options. Not sure if this works out. Please give it a try.

**Comment by UweSauter** [comment]
Would you mind creating the release for 1.1.3 so that iobroker can load it from Github…?

**Comment by Grizzelbee** [comment]
> Would you mind creating the release for 1.1.3 so that iobroker can load it from Github…?

sorry for missing that. Is online now.

**Comment by UweSauter** [comment]
One step at a time: `Error: Unable to complete value {"key":0,"value":{"valueId":"THolyCool"}}`

[debug.resol.0.zip](https://github.com/Grizzelbee/ioBroker.resol/files/8583021/debug.resol.0.zip)

**Comment by Grizzelbee** [comment]
Next try ... I'm pretty enthusiastic ... ;o)

**Comment by Grizzelbee** [comment]
Faking a DeltaSol-E doesn't work out. Therefore I removed all controll options from the config file. So V1.1.5 may work without errors, but it will not be able to control anything and since I don't own a Cosmo controller I can't figure it out. So if you need to control something (Rückkühlung, Pumps, ...) you need to figure it out on your own and I will be glad to build a release of it.

You can find a how-to in the readme and if you need help - don't hesitate to ask for it in the ioBroker forum. @gargano and me will provide as much help as we can.

**Comment by UweSauter** [comment]
Well darn…

Yes, 1.1.5 does not show any more errors on start up and that was the primary issue so thank you.

I'll try to have a look if I can decode the messages between Cosmo's Windows based software and the controller but depending on life that might take a while.

**Comment by Grizzelbee** [comment]
> Yes, 1.1.5 does not show any more errors on start up and that was the primary issue so thank you.

You're welcome!

> I'll try to have a look if I can decode the messages between Cosmo's Windows based software and the controller

It's more about reading some documentation and playing around with the adapters' config files. But I'm glad that it works at last.
